name: CI

on:
  push:
    tags:
      - "v[0-9]*"

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check generated files and formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Check generated files
        run: scripts/generate.php --check

      - name: Install PrettyPHP
        run: composer create-project --no-interaction --no-progress --no-dev lkrms/pretty-php=0.4.29 build/pretty-php

      - name: Run PrettyPHP
        run: build/pretty-php/bin/pretty-php --diff

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    needs: check

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "7.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan

  unit-tests:
    name: PHPUnit tests
    needs: check

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        php-version:
          - "8.2"
        include:
          - os: ubuntu-latest
            php-version: "8.1"
          - os: ubuntu-latest
            php-version: "8.0"
          - os: ubuntu-latest
            php-version: "7.4"
          - os: windows-latest
            php-version: "7.4"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: sqlite3
          coverage: pcov

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress
          npm install -g @mockoon/cli

      - name: Start Mockoon CLI
        shell: bash
        run: mockoon-cli start --port 3001 --log-transaction --data tests/fixtures/.mockoon/JsonPlaceholderApi.json &

      - name: Run PHPUnit tests and generate code coverage report
        run: vendor/bin/phpunit --no-coverage --coverage-clover=coverage.xml
        env:
          JSON_PLACEHOLDER_BASE_URL: "http://localhost:3001"

      - name: Upload Mockoon CLI log files artifact
        uses: actions/upload-artifact@v3
        with:
          name: mockoon-cli-logs-${{ matrix.os }}-${{ matrix.php-version }}
          path: ~/.mockoon-cli/logs/*.log

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
